plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
}

version = "${rootProject.mod_version}-mc${rootProject.minecraft_version}"
group = project.maven_group
base.archivesName = rootProject.mod_id

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
	mavenLocal() 
	maven { url = "https://api.modrinth.com/maven" }
    maven { url = "https://maven.terraformersmc.com/releases/" }
}

loom {
	splitEnvironmentSourceSets()
	mods {
		"newsfeed" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modImplementation include("org.apache.commons:commons-collections4:${collections_version}")
	modImplementation include("org.jdom:jdom2:${project.jdom_version}")
	modImplementation include("com.rometools:rome:${project.rome_version}")
	modImplementation include("com.rometools:rome-utils:${project.rome_version}")
	modImplementation include("org.json:json:${project.json_java_version}")
    modImplementation include("com.dorkbox:Notify:${project.notify_version}")
    modImplementation include("io.github.sandydunlop:cupra:${project.cupra_version}")
    modImplementation include("io.github.sandydunlop:cupra-minecraft:${project.cupra_minecraft_version}")
	modApi "com.terraformersmc:modmenu:${project.mod_menu_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
    // withJavadocJar()
	// withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}
